Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

IdentityMatrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.24587786, 0.35573   , 0.16887078, 0.63509717, 0.15806572])

In [20]:
np.random.rand(5,5)

array([[0.03901837, 0.855903  , 0.07980127, 0.64366132, 0.65100442],
       [0.49522107, 0.86417424, 0.52483219, 0.96523446, 0.27278867],
       [0.55859289, 0.19621191, 0.12636252, 0.01293036, 0.47640889],
       [0.12086137, 0.21733505, 0.90632216, 0.03829424, 0.38608187],
       [0.99409405, 0.86545479, 0.67847192, 0.46529836, 0.73263734]])

In [21]:
np.random.randn(2)

array([-0.93024398,  0.23571781])

In [22]:
np.random.rand(4,4)

array([[0.63852472, 0.75660758, 0.26503546, 0.61520001],
       [0.80817186, 0.96479204, 0.67989892, 0.56774406],
       [0.08129721, 0.73870162, 0.34165323, 0.38623764],
       [0.44049238, 0.00756737, 0.09872293, 0.44305711]])

In [23]:
np.random.randint(1,100)

57

In [24]:
np.random.randint(1,100,5)

array([61, 95, 42, 36, 34])

In [25]:
arr = np.arange(25)
ranrr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranrr

array([30, 30, 10, 17, 19, 38, 19, 11, 20, 26])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranrr.max()

38

In [30]:
ranrr.min()

10

In [31]:
ranrr.argmax()

5

In [32]:
ranrr.argmin()

2

In [33]:
arr.shape

(25,)

In [34]:
arr=arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int64')